apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-authen
  namespace: argocd
  labels:
    app: flask-authen
    env: production
    component: backend
    managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: "ServerSideDiff=true"
spec:
  project: default
  source:
    repoURL: https://github.com/khanhquoc4114/flask-authen-manifest
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-authen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - PrunePropagationPolicy=foreground
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Secret
    jsonPointers:
    - /data