apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: flask-authen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: backend-container
        image: wuoc4114/flask-authen-backend:541e3ce89d001beb4ad5898775ea7a3abdffe417
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: POSTGRES_HOST
            value: "postgres-service"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "db"
          - name: POSTGRES_USER
            value: "db"
          - name: POSTGRES_PASSWORD
            value: "db"
        envFrom:
        - secretRef:
            name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: flask-authen
spec:
  type: ClusterIP
  selector:
    app: flask-backend
  ports:
    - port: 8000
      targetPort: 8000