apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
  namespace: flask-authen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
      - name: frontend-container
        image: wuoc4114/flask-authen-frontend:2e4a2d4b739162812a15d171c149d202c2ebb287
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: flask-authen
spec:
  type: LoadBalancer
  selector:
    app: flask-frontend
  ports:
    - port: 80
      targetPort: 80