apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
  namespace: flask-authen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
      - name: frontend-container
        image: wuoc4114/flask-authen-frontend:8407cb46cc6504070533d9f1c31a9297c9762e60
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: flask-authen
spec:
  type: LoadBalancer
  selector:
    app: flask-frontend
  ports:
    - port: 3000
      targetPort: 3000