# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: flask-authen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: backend-container
        image: wuoc4114/flask-authen-backend:${GIT_SHA}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: flask-authen
spec:
  type: ClusterIP
  selector:
    app: flask-backend
  ports:
    - port: 5000
      targetPort: 5000

---

# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
  namespace: flask-authen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
      - name: frontend-container
        image: wuoc4114/flask-authen-frontend:${GIT_SHA}   # <--- CI/CD update
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: flask-authen
spec:
  type: LoadBalancer
  selector:
    app: flask-frontend
  ports:
    - port: 80
      targetPort: 80
