apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-authen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: wuoc4114/flask-authen:3a5e69dac8742b97d5f66eb81b987072119adc9c
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-authen
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - port: 80
      targetPort: 5000
